-- Seed data.
-- Loaded automatically by `supabase db reset` (see [db.seed] in supabase/config.toml).
--
-- Deliberately empty: real data (shops, users, super admin) is provisioned
-- through migrations / the dashboard UI, not by seeding fake accounts.